# Taps
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'heroku/brew'

# Install CLI Tools
## Shell Utilities
brew 'zsh'
brew 'jq'
brew 'docker-compose'
brew 'ack'
brew 'autojump' # faster navigation through directories

# brew 'coreutils' # (many already in macOS terminal)
# brew 'findutils' # (many already in macOS terminal)
# brew 'zsh-completions' # (not easily installed with oh-my-zsh)
# brew 'tmux' # (terminal session management)
# brew 'q' # (run SQL like queries on CSVs)

## Network Utilities
brew 'htop'
brew 'wget'
brew 'nmap' # (network and port scanner)

# brew 'mtr' # (traceroute and ping combined)

## System Utilities
brew 'tree' # (creates terminal tree of directories and websites)
brew 'mas'
brew 'trash' # (CLI tool to move file or folder to Trash)

# brew 'mackup' # (back up and restore Mac settings)
# brew 'terminal-notifier' # (create Mac notification from terminal)

## Dev Utilities
brew 'git'
brew 'awscli'
brew 'node'
brew 'diff-so-fancy'
brew 'heroku'
brew 'w3m' # (text based web browser, like Lynx)
brew 'nvm' # (use different versions of npm)

# brew 'reattach-to-user-namespace' # (tool for tmux)


# Mac Apps
## Communication
cask 'slack'
cask 'skype'

## Productivity
cask 'alfred'
cask 'google-chrome'

cask 'go2shell'
cask 'docker'
cask 'rectangle'
cask 'keycastr'
cask 'clipy'
cask 'cheatsheet'

## System
cask 'skitch'
cask 'the-unarchiver'
cask 'coconutbattery'
cask 'appcleaner'
cask 'namechanger'

## Editor
cask 'pycharm'
cask 'macdown'
brew 'vim'
# cask 'visual-studio-code'

## Development
cask 'iterm2'
cask 'postman'

cask 'atext'
cask 'diffmerge'
cask 'fastlane'
cask 'firefox'
cask 'gas-mask'
cask 'gpg-suite'
cask 'imageoptim'
cask 'java8'
cask 'ngrok'
cask 'robo-3t'
cask 'sequel-pro'
cask 'psequel'
cask 'sourcetree'

# Fonts
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'

# App
mas 'XCode', id: 497799835